name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: actions/cache@v2
                with:
                    path: |
                        ${{ steps.composer-cache.outputs.dir }}
                        vendor
                        vendor-bin
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install Composer
                uses: php-actions/composer@v1

            -   name: Composer Normalize
                uses: "docker://ergebnis/composer-normalize-action:latest"
                with:
                    args: "--indent-size 4 --indent-style space --dry-run"

            -   name: PHP CS Fixer
                run: "./vendor/bin/php-cs-fixer fix --diff --config vendor-bin/test/vendor/21torr/php-cs/.php_cs.dist --dry-run --no-interaction"

            -   name: Psalm
                run: "./vendor/bin/psalm --threads=4 -c vendor-bin/test/vendor/21torr/php-cs/psalm.xml"